userfname = input('Please enter your first name: ')
userlname = input('Please enter your last name: ')
user_dob = input('please enter your Date of birth: ')
user_course = input('Please enter your course name: ')
user_resident = input('Please enter if you are a uk resident or not (Yes or No): ')
user_age = int(input('How old are you? '))
user_address = input('Where do you live? ')

print("Welcome " + userfname + " " + userlname)
print(userfname.isalpha())
print(userlname.isalpha())
print("You were born on" + user_dob)
print("You study " + user_course.upper())
print(user_resident.capitalize())
print(f"You are {user_age} years old")
print("your door number is " + user_address[0:3])
print("your road name is " + user_address[4:])
